### ISSUE TITLE
Validation broken in mnist-keras

### ISSUE THREAD

**Issue by ahellander** [scaleoutsystems/fedn#242]
**Severity**
- [] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [x ] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [ ] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
The validation errors for mnist-keras in current develop.  

2021-08-18 13:48:16,345 - root - INFO -     y_pred = model.predict_classes(x_test)

08/18/2021 01:48:16 PM [process.py:14] AttributeError: 'Sequential' object has no attribute 'predict_classes'

2021-08-18 13:48:16,345 - root - INFO - AttributeError: 'Sequential' object has no attribute 'predict_classes'

08/18/2021 01:48:16 PM [dispatcher.py:28] DONE RUNNING validate /tmp/tmpaiyib12_.npz /tmp/tmp2di2m2ds
2021-08-18 13:48:16,683 - fedn.utils.dispatcher - INFO - DONE RUNNING validate /tmp/tmpaiyib12_.npz /tmp/tmp2di2m2ds
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/src/fedn/fedn/fedn/client.py", line 259, in __listen_to_model_validation_request_stream
    metrics = self.__process_validation_request(model_id)
  File "/app/src/fedn/fedn/fedn/client.py", line 346, in __process_validation_request
    validation = json.loads(fh.read())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Environment:**
 - OS: [e.g. mac OS]
 - Version: [e.g. macOS Catalina]

**Reproduction Steps**
Run the mnist-keras test. 

**Expected behavior**

**Screenshots**

**Contact Details**
An e-mail address in case we need to contact you for further details regarding this issue.

**Comment by ahellander** [comment]
The problem is related to release of TF 2.6.0. Temporary fix downgrades to tensorflow<2.6.0. We should later update the client code to work with 2.6.0.
