### ISSUE TITLE
Quickstart mnist-pytorch Jinja error

### ISSUE THREAD

**Issue by dalmouiee** [scaleoutsystems/fedn#468]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [x] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [ ] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
I am trying to run through the quickstart example on the main readme document, however I am facing issues with trying to setup the environment. There were a few issues with the creation of package modules that I bypassed by restructuring the directories and managed to generate package and seed, however when I navigate to `http://localhost:8090/context` by clickin gon the "\here" button on the main fedn UI, I get the following Jinja error:

```python
TemplateNotFound
jinja2.exceptions.TemplateNotFound: context.html

Traceback (most recent call last)
File "/venv/lib/python3.9/site-packages/flask/app.py", line 2552, in __call__
return self.wsgi_app(environ, start_response)
File "/venv/lib/python3.9/site-packages/flask/app.py", line 2532, in wsgi_app
response = self.handle_exception(e)
File "/venv/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
response = self.full_dispatch_request()
File "/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
rv = self.dispatch_request()
File "/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/fedn/fedn/clients/reducer/restservice.py", line 917, in context
File "/venv/lib/python3.9/site-packages/flask/templating.py", line 146, in render_template
template = app.jinja_env.get_or_select_template(template_name_or_list)
File "/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
return self._load_template(name, globals)
File "/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
template = self.loader.load(self, name, self.make_globals(globals))
File "/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
source, filename, uptodate = self.get_source(environment, name)
File "/venv/lib/python3.9/site-packages/flask/templating.py", line 62, in get_source
return self._get_source_fast(environment, template)
File "/venv/lib/python3.9/site-packages/flask/templating.py", line 98, in _get_source_fast
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: context.html
```

I ran the docker compose successfully and can open the main page as well.

**Environment:**
 - OS: macOS 
 - Version: macOS Ventura 13.2.1
 - Browser: Chrome
 - Version: 113.0.5672.126

**Reproduction Steps**
1. Run through the example quickstart for mnist-tensorflow
2. When you reach the step of uploading the package and seed, attempt to access the "/here" button
3. You will get the above error

**Expected behavior**
To show the page for uploading the package and seed

**Screenshots**
<img width="1437" alt="Screenshot 2023-06-01 at 11 38 54 am" src="https://github.com/scaleoutsystems/fedn/assets/22187309/d298a766-92ab-4147-aa06-6e519173fa8e">

**Contact Details**
d.almouiee@unsw.edu.au

**Comment by Wrede** [comment]
Thanks for the report! Will try to reproduce asap.

**Comment by dalmouiee** [comment]
> Thanks for the report! Will try to reproduce asap.

Hello any feedback on this? :)

**Comment by Wrede** [comment]
> > Thanks for the report! Will try to reproduce asap.
> 
> Hello any feedback on this? :)

Yes! I have not been able to reproduce the error you get. Are you experiencing the same error if you use a different browser? Also, can you please provide which version or branch  of FEDn you are using?

**Comment by dalmouiee** [comment]
> > > Thanks for the report! Will try to reproduce asap.
> > 
> > 
> > Hello any feedback on this? :)
> 
> Yes! I have not been able to reproduce the error you get. Are you experiencing the same error if you use a different browser? Also, can you please provide which version or branch of FEDn you are using?

Hi Fredrik, thanks for your response. I've actually just cloned the repo as is and following the readme quickstart immediately after cloning (so just working off of `master`). It's quite weird, I've pulled the latest version of `master` now and restarted the docker compose quickstart and the containers are not working, particularly the mongo containers are just restarting and the reducer stops due to the Mongo not working. I've deleted the repo and started from scratch but the docker compose is still not working for the quickstart tutorial. Are there any quickstart tutorials you can guide me to to get a quick working example of FedN please?

I've attached a snapshot of the errors I'm getting from the Mongo and reducer containers:

<img width="1196" alt="Screenshot 2023-06-14 at 8 43 55 pm" src="https://github.com/scaleoutsystems/fedn/assets/22187309/3122f6b4-1c5d-4dc1-a4d7-7db7e1935c98">
<img width="1191" alt="Screenshot 2023-06-14 at 8 44 37 pm" src="https://github.com/scaleoutsystems/fedn/assets/22187309/db696a3f-c8bd-4bc5-9a2f-8ca2b8a671c6">
<img width="1163" alt="Screenshot 2023-06-14 at 8 44 08 pm" src="https://github.com/scaleoutsystems/fedn/assets/22187309/0c1408eb-f8f6-4e3f-a79d-98caa2c5cdfd">

**Comment by Wrede** [comment]
Try this and after see if you still have problems. OBS this will delete dangling images, cache and unused volumes! 
`docker system prune --volumes`

Then run:
`docker-compose down -v`
`docker-compose up -d`

Let me know if you still get exit code 100 from mongo.

**Comment by dalmouiee** [comment]
> Try this and after see if you still have problems. OBS this will delete dangling images, cache and unused volumes! `docker system prune --volumes`
> 
> Then run: `docker-compose down -v` `docker-compose up -d`
> 
> Let me know if you still get exit code 100 from mongo.

Thanks a lot! I got it working now and my initial problem is not appearing any longer :)
