### ISSUE TITLE
fedn:develop-mnist-pytorch image contains old codebase 

### ISSUE THREAD

**Issue by dalmouiee** [scaleoutsystems/fedn#471]
**Severity**
- [ ] Critical/Blocker (select if the issue makes the application unusable or causes serious data loss)
- [x] High (select if the issue affects a major feature and there is no workaround or the available workaround is very complex)
- [ ] Medium (select if the issue affects a minor feature or affects a major feature but has an easy enough workaround to not cause any major inconvenience)
- [ ] Low (select if the issue doesn't significantly affect the user experience, like minor visual bugs)

**Describe the bug**
When attempting to run the command
```
 docker run \
-v $PWD/client.yaml:/app/client.yaml \
-v $PWD/data/clients/1:/var/data \
-e ENTRYPOINT_OPTS=--data_path=/var/data/mnist.pt \
--network=fedn_default \
ghcr.io/scaleoutsystems/fedn/fedn:develop-mnist-pytorch run client -in client.yaml --name client1
```
I get the following error and the container stops running:
```
Running Dispatcher for entrypoint: startup
Traceback (most recent call last):
  File "/venv/bin/fedn", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/fedn/cli/run_cmd.py", line 144, in client_cmd
    client = Client(config)
  File "/app/fedn/fedn/network/clients/client.py", line 103, in __init__
    self._initialize_helper(client_config)
  File "/app/fedn/fedn/network/clients/client.py", line 146, in _initialize_helper
    self.helper = get_helper(client_config['model_type'])
  File "/app/fedn/fedn/utils/helpers.py", line 16, in get_helper
    helper = importlib.import_module(helper_plugin)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fedn.utils.plugins.pytorch'
```

It appears that the image contains outdated code that is no longer in the current SDK? 

**Environment:**
 - OS: MacOS
 - Version: Ventura
 - Browser: Chrome

**Reproduction Steps**
1. Follow the quickstart guide for the MNIST pytorch example.
2. Run the above command in a terminal.

**Expected behavior**
Expect image to run successfully with no errors.

**Screenshot**
<img width="753" alt="Screenshot 2023-06-14 at 10 15 51 pm" src="https://github.com/scaleoutsystems/fedn/assets/22187309/b57915cc-f214-43c0-9baa-e0c4a25255ed">

**Contact Details**
d.almouiee@unsw.edu.au

**Comment by Wrede** [comment]
If you were following README at master branch, the image tag is a typo, it should be:
ghcr.io/scaleoutsystems/fedn/fedn:master-mnist-pytorch
